### ISSUE TITLE
className/style props

### ISSUE THREAD

**Issue by kachkaev** [kristw/react-vega#1]
Hi @kristw, thanks for the wrapper! Vega is great by itself and is even better with React! 

What do you think of adding `className` prop to `<Vega />`? This can be useful for positioning the vis without having to wrap it into an extra component. Maybe having an option to add `style` to the div that's being rendered can be useful to somebody.

The only complexity this will create will be in slightly changed conditions inside the lifecycle hooks (we may need to re-render because of a new `className` or `style`, but keep vega stuff as is).

**Comment by kristw** [comment]
I have included `className` and `style` in the 2.2.0 release.
