### ISSUE TITLE
Tooltip Handler Support Needed

### ISSUE THREAD

**Issue by mdelrossi1** [kristw/react-vega#18]
The 3.x.x vega view API has a tooltip handler that would be nice to add to react-vega.  I've created a PR with the work that I think is necessary for this support in #17.  Let me know if there is anything that needs updating or was missed in the PR or if there is already support for it and I can update/close accordingly.

**Comment by mdelrossi1** [comment]
@kristw When would you have the time to address this issue?

**Comment by kristw** [comment]
Merged and published v4.0.0. Thanks for your pull request.
