### ISSUE TITLE
vega-lite support

### ISSUE THREAD

**Issue by juanpr2** [kristw/react-vega#3]
Would it be possible to add support for `vega-lite`.
It could be passed as an option to the `props`, for example
`<Vega spec={spec} renderer="vega-lite" />`

**Comment by kristw** [comment]
I was about to do the above but then it would mean `react-vega` will also depend on `vega-lite`, which could be undesirable for user who are interested in using vega only. To avoid unnecessary dependency, I have created another lib `react-vega-lite`, which works very similar to `react-vega`
https://github.com/kristw/react-vega-lite

**Comment by kristw** [comment]
I would close this for now. Hope it address your proposal. If you have any feedback or issue, please feel free to add to `react-vega-lite` issues. Thanks!
