### ISSUE TITLE
node version in package.json

### ISSUE THREAD

**Issue by kachkaev** [kristw/react-vega#5]
Hi @kristw!

I just tried a new package manager called [yarn](https://yarnpkg.com/), which was announced only a couple of hours ago. Running `yarn` for one of my existing projects failed with the following output:

```
[2/4] Fetching packages...
error react-vega@2.3.0: The engine "node" is incompatible with this module. Expected version "~5.2".
error Found incompatible module
```

Seems like the issue is in these lines inside `package.json`:

```json
"engines": {
    "node": "~5.2"
},
```

My node version is `6.6.0`.

Given that there are no problems with `react-vega` in node 6, could you please make the engine restriction a bit less strict please? Hope it takes only one minute.

**Comment by kristw** [comment]
Done. Please try `react-vega` 2.3.1

**Comment by kachkaev** [comment]
Awesome! I'll try that tomorrow!  🎉

**Comment by kachkaev** [comment]
It worked, thanks a lot for such a quick response Krist!
