### ISSUE TITLE
Support Vega 3.x

### ISSUE THREAD

**Issue by jfsiii** [kristw/react-vega#6]
Vega is now at `v3.0.0-beta.25`. The [Vega homepage](https://vega.github.io/vega/) & [examples ](https://vega.github.io/vega/examples/) have been updated to use the v3 schemas.

See the [porting guide](https://vega.github.io/vega/docs/porting-guide/) for info on converting v2 schemas to v3.

**Comment by kristw** [comment]
Thanks for pointing out. I might wait a bit until it's out of beta.

**Comment by kristw** [comment]
Done in v3.0.0 release
