### ISSUE TITLE
'prop-types' warning in v2

### ISSUE THREAD

**Issue by kachkaev** [kristw/react-vega#8]
It'd be great if this pretty common warning was addressed in v2:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

It's likely that the corresponding version of Vega will be around for some time before v3 becomes dominant. How feasible would it be to release `react-vega@2.3.2` with the fix?

**Comment by kristw** [comment]
Done. Please try 2.3.2
