### ISSUE TITLE
Dynamically loading data does not seem to work

### ISSUE THREAD

**Issue by lieutenantsauce** [kristw/react-vega#9]
I am attempting to render a chart from data in a json file and the datapoints do not seem to render. Source code for a repro case is [here]( https://github.com/lieutenantsauce/vega-test). A screenshot of the output case is attached. 

Any help would be greatly appreciated. Thanks.

**Comment by lieutenantsauce** [comment]
<img width="380" alt="chart" src="https://cloud.githubusercontent.com/assets/26468311/26239875/bbd6192e-3c33-11e7-84cd-81db2c97283a.png">

**Comment by kristw** [comment]
Hi, 

I think there are two issues:

1. You are not parsing the date correctly.

```
const parseTime = dl.format.time('%Y-%m-%d');
// parseTime is a function to format time, not parse time
```

![image](https://cloud.githubusercontent.com/assets/1659771/26389491/05dcf8ba-400f-11e7-91f8-1e17ac1ac009.png)

2. I switched renderer to svg and see that the data are passed to the chart component correctly, but the drawn path always has x at 0. You may want to debug your vega spec a bit.

```
<path d="M0,91.266175L0,82.4866L0,20.833574999999993L0,51.73052499999999L0,55.2377L0,113.40315000000001L0,130.365725L0,59.9515L0,51.304225L0,43.77537499999999L0,59.63055000000001L0,58.7853L0,117.18349999999998L0,122.53307500000001L0,58.94822499999999L0,15.97032499999999L0,21.99242499999999L0,74.86955L0,33.157075L0,90.389075L0,109.094825L0,60.018874999999994L0,50.686825000000006L0,31.74465L0,20.850724999999997L0,16.222674999999988L0,105.98945L0,107.31490000000001L0,70.04059999999998L0,196" style="fill: steelblue; stroke: rgb(83, 87, 161); stroke-width: 2;"></path>
```

**Comment by lieutenantsauce** [comment]
thanks, your hints were very helpful. I now have a working vega visualization. happy days. 👍 

closing this issue.
